### PR TITLE
Remove recently added support for symlinks

### PR DESCRIPTION
**Pull request by andy5995**
This partially reverts #462

### CODE REVIEW

**Comment by ccoVeille** [comment]
Any explanation that would come with the PR?

**Comment by andy5995** [comment]
@ccoVeille This just means that any waste folder folder defined in your config file must not be a symbolic link. In the future, any waste folder defined using a symlink will be ignored and not used.

**Comment by andy5995** [comment]
The [trash spec](https://specifications.freedesktop.org/trash-spec/1.0/#id-1.6.10.1) mentions symbolic links only once:

>When trashing a file from a non-home partition/device [[4]](https://specifications.freedesktop.org/trash-spec/1.0/#ftn.id-1.6.10.1) , an implementation (if it supports trashing in top directories) MUST check for the presence of $topdir/.Trash.

>When preparing a list of all trashed files (for example, to show to the user), an implementation also MUST check for .Trash in all top directories that are known to it.

>If this directory is present, the implementation MUST, by default, check for the “sticky bit”. (It MAY provide a way for the administrator, and only the administrator, to disable this checking for a particular top directory, in order to support file systems that do not have the “sticky bit”).

>The implementation also MUST check that this directory is not a symbolic link.

I'm a bit confused by it. But I don't see why anyone would need a symbolic link. They can just define directory the symlink points to. For other desktop trash systems where trash dirs can't be defined, I see where it might be useful. Like in the case where @luigir-it has a symlink to their btrfs subvolume. But with rmw, they can just put the actual directory in the rmw config file.

**Comment by ccoVeille** [comment]
Thanks it's clearer

**Pull request merged**
