### PR TITLE
c-cpp.yml:add test for FreeBSD

### PR DESCRIPTION
**Pull request by andy5995**
See https://github.com/vmactions/freebsd-vm for more info

### CODE REVIEW

**Comment by andy5995** [comment]
@Neilpang Sorry to bother you, but I was trying out your [FreeBSD GitHub runner vm](https://github.com/vmactions/freebsd-vm) with this project, but it's failing to find the menu or menuw library. That's not a problem with your vm, but I was wondering if you know how I could fix that in my meson build? the output is at [L1616](https://github.com/theimpossibleastronaut/rmw/runs/4678329216?check_suite_focus=true#step:3:1616)

**Comment by Neilpang** [comment]
You  can use this project to login and debug :
https://github.com/vmactions/shell-freebsd

**Comment by andy5995** [comment]
> You can use this project to login and debug : https://github.com/vmactions/shell-freebsd

Thanks @Neilpang I'm trying it now. I'm in the shell but `pkg` isn't present. How can I install meson and ninja?

**Comment by andy5995** [comment]
> > You can use this project to login and debug : https://github.com/vmactions/shell-freebsd
> 
> Thanks @Neilpang I'm trying it now. I'm in the shell but `pkg` isn't present. How can I install meson and ninja?

oh.. I'll use brew!

**Comment by andy5995** [comment]
Trying to build on [NomadBSD](https://nomadbsd.org/), before any changes, meson was able to find the menu library.

image


Screenshot_2022-01-07_23-42-34

On the VM I added to the workflow, the menu library can't be found. I tried figuring out why by using the project @Neilpang mentioned above, but I could not.

A few things needed changing in the meson build anyway, which I did, and I also edited some of the code so rmw would build even if neither of those libs are found (rmw -s won't work).

**Comment by andy5995** [comment]
I edited meson.build to use the find_library() method to find the menu library. Works in the FreeBSD VM and also on OpenBSD 7.0. [The PR](https://github.com/theimpossibleastronaut/rmw/pull/334) will be merged soon.

**Pull request merged**
