### PR TITLE
ci: refactor main workflow

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
@bbonev Would you like any tests like these added to the [yascreen](https://github.com/bbonev/yascreen) CI?

**Comment by bbonev** [comment]
I just briefly skimmed through the diff, looks like this needs more work before it becomes good to merge.

E.g.:

    brew install ncurses

and

    run: cd builddir && meson test -v

and

    run: cd builddir && meson test -v --setup=fake_media_root --suite rmw

and

    meson compile
    meson test -v
    meson test -v --setup=fake_media_root --suite rmw

look like leftovers from another project...

**Comment by andy5995** [comment]
@bbonev Thanks for looking it over! I'll explain a little below...

> I just briefly skimmed through the diff, looks like this needs more work before it becomes good to merge.
> 
> E.g.:
> 
> ```
> brew install ncurses
> ```

The ncurses installed on macos doesn't include widechar support, so I install it with brew.


> and
> 
> ```
> run: cd builddir && meson test -v
> ```

Because it's on a different step, I need to change back to the builddir. Basically the environment isn't saved.

The other way to do it is

```
      run: |
        meson setup builddir
        cd builddir
        meson compile
        meson test -v
        meson test -v --setup=fake_media_root --suite rmw
```

The disadvantage to that approach is that in the actions log, if any steps failed, it's not as obvious.

I might do it that way anyway. Thanks for the perspective. :)

**Comment by andy5995** [comment]
> Oopsie, I got confused ;)
> 
> This is `rmw` project, not `yascreen` B-) I somehow got the impression that this is a pull to `yascreen`...

Happens to me all the time. :) A person gets so used to working on their own project they don't notice when they're on someone else's. ;)

Let me know if you'd like me add some extra tests like this to yascreen. Macos, clang on Ubuntu, FreeBSD, slackware, etc.

**Comment by bbonev** [comment]
Yes, please. The main difference is if the library is linked with symbol versioning or not.

**Pull request merged**
