### PR TITLE
replace rm with embedded BSD coreutils rm

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
@DiegoMagdaleno I get errors when building on macos https://github.com/theimpossibleastronaut/rmw/actions/runs/4002064406/jobs/6868938665

Is BSDCoreUtils intended to run on macos or just on Linux? Also getting error on FreeBSD... https://github.com/theimpossibleastronaut/rmw/actions/runs/4002064406/jobs/6868938848#step:3:1462

**Comment by DiegoMagdaleno** [comment]
It is intended to work on macOS, it looks like the issue is related to the definition of macOS guid and uid, I can try checking the error out tomorrow.

As for FreeBSD, at least in the logs, I can't see the error, it just says "Bash exited with error code 1"

I guess my workaround for the definitions of said functions (guid and uid) got broken in some updates after I stopped used macOS, I will check it out.

**Comment by DiegoMagdaleno** [comment]
@andy5995 I did a quick commit, try to checkout if that fixes the issue.

**Comment by andy5995** [comment]
> @andy5995 I did a quick commit, try to checkout if that fixes the issue.

It did! Thanks!

The errors from the FreeBSD build are in the txt file attached. 11 of them.


[3_Test.txt](https://github.com/theimpossibleastronaut/rmw/files/10495795/3_Test.txt)

**Comment by DiegoMagdaleno** [comment]
For FreeBSD I am able to notice the issue, it looks like the compatibility library might need some changes when on FreeBSD.

Due to my timezone and University I'll be checking FreeBSD issues tomorrow, once I setup a virtual machine.

Thank for helping in diverse compatibility checks.

**Comment by andy5995** [comment]
Sure, there is no rush. Get some rest! I appreciate your help.

**Comment by DiegoMagdaleno** [comment]
@andy5995 I added some fixes for FreeBSD, can you please check if some errors are fixed?

**Comment by DiegoMagdaleno** [comment]
I pushed some more fixes, should fix some declaration issues..

**Comment by andy5995** [comment]
@DiegoMagdaleno I just applied your second patch now. We'll see shortly if it works. Thanks!

**Comment by andy5995** [comment]
> I pushed some more fixes, should fix some declaration issues..

Working now! All builds completing and tests passing. :)

**Comment by DiegoMagdaleno** [comment]
Great!

**Pull request merged**
