### PR TITLE
issue release v0.7.07

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
Maybe I could ping @elextr in case he's got a little extra time and interest to test out the branch...

**Review by sexybiggetje — DISMISSED** [review]
Seems legit to me, I've reviewed the commits by hand in the web ui

**Comment by andy5995** [comment]
Thanks @sexybiggetje !

**Comment by andy5995** [comment]
I noticed a new bug... I'm sure I introduced it recently... With  `rmw -l`, all removable devices show as attached even if they are not.

I'll fix it tomorrow probably (before the release).

**Comment by andy5995** [comment]
> I noticed a new bug... I'm sure I introduced it recently... With `rmw -l`, all removable devices show as attached even if they are not.
> 
> I'll fix it tomorrow probably (before the release).

fixed on master and rebased

**Pull request merged**
