### PR TITLE
Release/v0.7.09

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Review by sexybiggetje — APPROVED** [review]
I saw some German in here, I'm not sure of all the technical terms, but Papierkorb is literally for paper. Might Müll or Mülleimer (trash or trashcan/bucket) be a better translation?

**Comment by andy5995** [comment]
> I saw some German in here, I'm not sure of all the technical terms, but Papierkorb is literally for paper. Might Müll or Mülleimer (trash or trashcan/bucket) be a better translation?

@sexybiggetje , "Papierkorb" works well according to this: https://www.dict.cc/?s=Papierkorb

And btw, you might find this a more efficient way to make suggestions: https://til.hashrocket.com/posts/szgdi4at59-github-insert-a-suggestion-

**Comment by sexybiggetje** [comment]
I know, I found it more generic this way because it's at multiple places ☺️ it's used on the other review you requested 😅.

Enfin, my technical German isn't that great, so that's fine, I approved it anyway. Good job 🐷

**Comment by andy5995** [comment]
> I know, I found it more generic this way because it's at multiple places relaxed it's used on the other review you requested sweat_smile.
> 
> Enfin, my technical German isn't that great, so that's fine, I approved it anyway. Good job pig

Thanks @sexybiggetje :)

**Pull request merged**
