### PR TITLE
add extra gcc options

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
The only file I actually edited here was configure.ac https://github.com/theimpossibleastronaut/rmw/pull/286/files#diff-67e997bcfdac55191033d57a16d1408a ; all the other changes were made when running `autoconf` so only configure.ac needs review and feedback.

With the extra compiler options, there are more warnings now (as can be seen in the Travis log), which I'll fix in a separate patch.

**Comment by andy5995** [comment]
> With the extra compiler options, there are more warnings now (as can be seen in the Travis log), which can get fixed in a separate patch.

I fixed the warnings.

**Comment by Jammyjamjamman** [comment]
> > With the extra compiler options, there are more warnings now (as can be seen in the Travis log), which can get fixed in a separate patch.
> 
> I fixed the warnings.

I still get warnings about compiling with optimisations:

```
Making all in src
make[1]: Entering directory '/path/to/rmw/build/src'
make  all-am
make[2]: Entering directory '/path/to/rmw/build/src'
  CC       rmw-globals.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/globals.c:27:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-main.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/main.c:27:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-restore_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/restore_rmw.c:27:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-config_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/config_rmw.c:28:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-parse_cli_options.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/parse_cli_options.c:27:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-strings_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/strings_rmw.c:28:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-purging_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/purging_rmw.c:25:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-messages_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/messages_rmw.h:28,
                 from ../../src/messages_rmw.c:26:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-time_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/time_rmw.c:25:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-trashinfo_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/trashinfo_rmw.h:28,
                 from ../../src/trashinfo_rmw.c:25:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-utils_rmw.o
In file included from /usr/include/errno.h:25,
                 from ../../src/globals.h:31,
                 from ../../src/utils_rmw.c:28:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CC       rmw-bst.o
In file included from /usr/include/strings.h:21,
                 from ../../src/bst.h:5,
                 from ../../src/bst.c:14:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
  CCLD     rmw
make[2]: Leaving directory '/path/to/rmw/build/src'
make[1]: Leaving directory '/path/to/rmw/build/src'
Making all in man
make[1]: Entering directory '/path/to/rmw/build/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/path/to/rmw/build/man'
Making all in test
make[1]: Entering directory '/path/to/rmw/build/test'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/path/to/rmw/build/test'
Making all in po
make[1]: Entering directory '/path/to/rmw/build/po'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/path/to/rmw/build/po'
make[1]: Entering directory '/path/to/rmw/build'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/path/to/rmw/build'
```
Manjaro 20, gcc 10.

**Comment by andy5995** [comment]
> 
> I still get warnings about compiling with optimisations:

Thanks for testing, @Jammyjamjamman . This doesn't happen on Travis running Ubuntu Bionic, compiling with gcc 10.

Could you try with `make V=1` to see the actual gcc compile line and paste here please?

**Comment by andy5995** [comment]
@Jammyjamjamman this change should fix that for you. https://github.com/theimpossibleastronaut/rmw/commit/26dbafd4dc7d90b3c8b06a0cbb14c801a4b6db90#diff-67e997bcfdac55191033d57a16d1408a

After reading more about FORTIFY_SOURCE,  I think it'll be just fine if it's only added for a release.

Some extra details:

iirc, if a program is compiled with -g (debug symbols) optimizations should be set low or turned off or most debug symbols will be stripped away.

In configure.ac, you can see that that rmw is compiled with debug symbols and I think this might also add -O0, the zero not being high enough to satisfy FORTIFY_SOURCE

```
# A "yes" value will be overridden by the value returned by AX_IS_RELEASE()
AX_CHECK_ENABLE_DEBUG([yes])
```

For me and I think on Travis, -O2 (optimize level 2) is still on by default, in the CFLAGS variable, which is why I didn't see the same warnings as you. I'm not sure where that's being added from yet, but could cause a problem next time I use gdb. But anyway..

After you test this the normal way, you can run `make dist` to make an archive, untar it, use `make V=1` and you should see FORTIFY_SOURCE being added, and without those warnings.

**Comment by Jammyjamjamman** [comment]
Well. That removed that set of errors, but now I get a different set about overflows...
<details>
```
make V=1
Making all in src
make[1]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/src'
make  all-am
make[2]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/src'
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-globals.o `test -f 'globals.c' || echo '../../src/'`globals.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-main.o `test -f 'main.c' || echo '../../src/'`main.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-restore_rmw.o `test -f 'restore_rmw.c' || echo '../../src/'`restore_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-config_rmw.o `test -f 'config_rmw.c' || echo '../../src/'`config_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-parse_cli_options.o `test -f 'parse_cli_options.c' || echo '../../src/'`parse_cli_options.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-strings_rmw.o `test -f 'strings_rmw.c' || echo '../../src/'`strings_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-purging_rmw.o `test -f 'purging_rmw.c' || echo '../../src/'`purging_rmw.c
../../src/purging_rmw.c: In function ‘orphan_maint’:
../../src/purging_rmw.c:489:50: warning: ‘%s’ directive output may be truncated writing 10 bytes into a region of size between 1 and 4097 [-Wformat-truncation=]
  489 |       snprintf (path_to_trashinfo, req_len, "%s%s%s", waste_curr->info, st_file_properties.base_name,
      |                                                  ^~
In file included from /usr/include/stdio.h:867,
                 from ../../src/globals.h:34,
                 from ../../src/purging_rmw.c:25:
/usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 11 or more bytes (assuming 4107) into a destination of size 4097
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/purging_rmw.c:498:59: warning: ‘%s’ directive output may be truncated writing 9 bytes into a region of size between 1 and 4097 [-Wformat-truncation=]
  498 |       snprintf (st_file_properties.real_path, req_len, "%s%s%s", waste_curr->parent, "/orphans/",
      |                                                           ^~                         ~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from ../../src/globals.h:34,
                 from ../../src/purging_rmw.c:25:
/usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 10 or more bytes (assuming 4106) into a destination of size 4097
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-messages_rmw.o `test -f 'messages_rmw.c' || echo '../../src/'`messages_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-time_rmw.o `test -f 'time_rmw.c' || echo '../../src/'`time_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-trashinfo_rmw.o `test -f 'trashinfo_rmw.c' || echo '../../src/'`trashinfo_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-utils_rmw.o `test -f 'utils_rmw.c' || echo '../../src/'`utils_rmw.c
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-bst.o `test -f 'bst.c' || echo '../../src/'`bst.c
gcc -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses   -o rmw rmw-globals.o rmw-main.o rmw-restore_rmw.o rmw-config_rmw.o rmw-parse_cli_options.o rmw-strings_rmw.o rmw-purging_rmw.o rmw-messages_rmw.o rmw-time_rmw.o rmw-trashinfo_rmw.o rmw-utils_rmw.o rmw-bst.o -lmenu -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -lncursesw  
make[2]: Leaving directory '/path/to/rmw/build/rmw-0.7.06-dev/build/src'
make[1]: Leaving directory '/path/to/rmw/build/rmw-0.7.06-dev/build/src'
Making all in man
make[1]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/path/to/rmw/build/rmw-0.7.06-dev/build/man'
Making all in test
make[1]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/test'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/path/to/rmw/build/rmw-0.7.06-dev/build/test'
Making all in po
make[1]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/po'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/path/to/rmw/build/rmw-0.7.06-dev/build/po'
make[1]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/path/to/rmw/build/rmw-0.7.06-dev/build'
```
</details>

(Note: I extracted the repo into the `build/` folder of rmw because I'm lazy, but I don't think that should have affected anything.)

**Comment by andy5995** [comment]
> Well. That removed that set of errors, but now I get a different set about overflows...
> 
> ```
> make V=1
> Making all in src
> make[1]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/src'
> make  all-am
> make[2]: Entering directory '/path/to/rmw/build/rmw-0.7.06-dev/build/src'
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-globals.o `test -f 'globals.c' || echo '../../src/'`globals.c
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-main.o `test -f 'main.c' || echo '../../src/'`main.c
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-restore_rmw.o `test -f 'restore_rmw.c' || echo '../../src/'`restore_rmw.c
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-config_rmw.o `test -f 'config_rmw.c' || echo '../../src/'`config_rmw.c
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-parse_cli_options.o `test -f 'parse_cli_options.c' || echo '../../src/'`parse_cli_options.c
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-strings_rmw.o `test -f 'strings_rmw.c' || echo '../../src/'`strings_rmw.c
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wextra -fno-common -fstack-protector-strong -Werror=format-security -Wformat-overflow=2 -D_FORTIFY_SOURCE=2 -O2 -Wall -I/usr/local/include -I/usr/local/include/ncurses -c -o rmw-purging_rmw.o `test -f 'purging_rmw.c' || echo '../../src/'`purging_rmw.c
> ../../src/purging_rmw.c: In function ‘orphan_maint’:
> ../../src/purging_rmw.c:489:50: warning: ‘%s’ directive output may be truncated writing 10 bytes into a region of size between 1 and 4097 [-Wformat-truncation=]
>   489 |       snprintf (path_to_trashinfo, req_len, "%s%s%s", waste_curr->info, st_file_properties.base_name,
>       |                                                  ^~
> In file included from /usr/include/stdio.h:867,
>                  from ../../src/globals.h:34,
>                  from ../../src/purging_rmw.c:25:
> /usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 11 or more bytes (assuming 4107) into a destination of size 4097
>    67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    68 |        __bos (__s), __fmt, __va_arg_pack ());
>       |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../src/purging_rmw.c:498:59: warning: ‘%s’ directive output may be truncated writing 9 bytes into a region of size between 1 and 4097 [-Wformat-truncation=]
>   498 |       snprintf (st_file_properties.real_path, req_len, "%s%s%s", waste_curr->parent, "/orphans/",
>       |                                                           ^~                         ~~~~~~~~~~~
> In file included from /usr/include/stdio.h:867,
>                  from ../../src/globals.h:34,
>                  from ../../src/purging_rmw.c:25:
> /usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 10 or more bytes (assuming 4106) into a destination of size 4097
>    67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    68 |        __bos (__s), __fmt, __va_arg_pack ());
>       |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src    -D_DEFAULT_SOURCE 

I got something similar. After doing some reading, I'm not sure the best way to fix those yet.

> (Note: I extracted the repo into the `build/` folder of rmw because I'm lazy, but I don't think that should have affected anything.)

No, that's fine. But to make it easier, I added an arg to configure... `--enable-release` so you can just run that from your normal build directory, without creating a distribution archive. You shouldn't ever have to use that though except for testing.

**Pull request merged**
